<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'name' => 'Ján Lang',
                'email' => 'fiittim10@gmail.com',
                'password' => '$2y$10$yL0JX.ryxyQAo9WshBFWNuGKfsqqwqTbQx6VRJdDBPeOFuCF2xUbO',
                'remember_token' => '',
                'user_type_id' => 6,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 1,
				'class' => null,
            ),
            1 => 
            array (
                'name' => 'doc. Ing. Valentino Vranić, PhD.',
                'email' => 'vranic@stuba.sk',
                'password' => '$2y$10$IK3jaoZtKBQbDWDsfmdvr.0QmFx8Sp9qppCvT2r/0b5fbTqaR9ahq',
                'remember_token' => '',
                'user_type_id' => 4,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 1,
				'class' => null,
            ),
            2 => 
            array (
                'name' => 'Komisár',
                'email' => 'komisar@gmail.com',
                'password' => '$2y$10$yL0JX.ryxyQAo9WshBFWNuGKfsqqwqTbQx6VRJdDBPeOFuCF2xUbO',
                'remember_token' => '',
                'user_type_id' => 5,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => null,
				'class' => null,
            ),
            3 => 
            array (
                'name' => 'Autor',
                'email' => 'autor@gmail.com',
                'password' => '$2y$10$yL0JX.ryxyQAo9WshBFWNuGKfsqqwqTbQx6VRJdDBPeOFuCF2xUbO',
                'remember_token' => '',
                'user_type_id' => 3,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => null,
				'class' => null,
            ),
            4 => 
            array (
                'name' => 'Študent',
                'email' => 'student@gmail.com',
                'password' => '$2y$10$yL0JX.ryxyQAo9WshBFWNuGKfsqqwqTbQx6VRJdDBPeOFuCF2xUbO',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => null,
				'class' => null,
            ),
            5 => 
            array (
                'name' => 'Učiteľ',
                'email' => 'ucitel@gmail.com',
                'password' => '$2y$10$yL0JX.ryxyQAo9WshBFWNuGKfsqqwqTbQx6VRJdDBPeOFuCF2xUbO',
                'remember_token' => '',
                'user_type_id' => 3,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-04 19:59:54',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => null,
				'class' => null,
            ),
			6 => 
            array (
                'name' => 'Sabina Dudášová',
                'email' => 'dudasovasabina@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			7 => 
            array (
                'name' => 'Viktória Göndörová',
                'email' => 'gondorovav@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			8 => 
            array (
                'name' => 'Janka Halušková',
                'email' => 'janulka016@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			9 => 
            array (
                'name' => 'Slavka Halušková',
                'email' => 'slavula22@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			10 => 
            array (
                'name' => 'Laura Chovancová',
                'email' => 'ivana.chovanova12112005@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			11 => 
            array (
                'name' => 'Matúš Kmeť',
                'email' => 'matusko12042006@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			12 => 
            array (
                'name' => 'Ema Kováčová',
                'email' => 'emakovacova9@centrum.sk',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			13 => 
            array (
                'name' => 'Nina Kováčová',
                'email' => 'klejka.kovacova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			14 => 
            array (
                'name' => 'Maroš Kupec',
                'email' => 'kupcokmaros@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			15 => 
            array (
                'name' => 'Ľudmila Pomaj',
                'email' => 'lulupomaj8@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			16 => 
            array (
                'name' => 'Alexandra Štempelová',
                'email' => 'stempelovaalexandra@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			17 => 
            array (
                'name' => 'Paulína Heretová',
                'email' => 'paulusa2005@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			18 => 
            array (
                'name' => 'Nina Natália Vavreková',
                'email' => 'vavrekovanina@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			19 => 
            array (
                'name' => 'Jonáš Bábela',
                'email' => 'jonas.babela@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			20 => 
            array (
                'name' => 'Kristína Balková',
                'email' => 'kika.balkova94@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			21 => 
            array (
                'name' => 'Lucia Brndiarová',
                'email' => 'brndiarovalucia6@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			22 => 
            array (
                'name' => 'Milan Buček',
                'email' => 'eragoncity0987@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			23 => 
            array (
                'name' => 'Viera Dujničová',
                'email' => 'wrkdujnicova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			24 => 
            array (
                'name' => 'Martin Feranec',
                'email' => 'matoferanec@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1B - B. skupina',
            ),
			25 => 
            array (
                'name' => 'Lenka Ferenczová',
                'email' => 'lenka9.gina9@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			26 => 
            array (
                'name' => 'Emma Kyzúrová',
                'email' => 'emmakyzurova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			27 => 
            array (
                'name' => 'Zoja Lašáková',
                'email' => 'zojalasakova2112@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			28 => 
            array (
                'name' => 'Laura Megyeriová',
                'email' => 'lala.megy@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			29 => 
            array (
                'name' => 'Terézia Motyčková',
                'email' => 'terezia.motyckova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A, 1B - AB. skupina',
            ),
			30 => 
            array (
                'name' => 'Róbert Bejtic',
                'email' => 'r.bejtic@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			31 => 
            array (
                'name' => 'Róbert Biž',
                'email' => 'robko.biz@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			32 => 
            array (
                'name' => 'Alexandra Bokorová',
                'email' => 'alexbokorova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			33 => 
            array (
                'name' => 'Viktória Čipková',
                'email' => 'viktoria.cipkova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			34 => 
            array (
                'name' => 'Daniela Ďurejová',
                'email' => 'dandur32@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			35 => 
            array (
                'name' => 'Lucia Ďurišková',
                'email' => 'lucka410@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			36 => 
            array (
                'name' => 'Tomáš Hapl',
                'email' => 'tomhapl12@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			37 => 
            array (
                'name' => 'Anna Lacovičová',
                'email' => 'anna.lacovic@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			38 => 
            array (
                'name' => 'Sabina Lauríková',
                'email' => 'laurikovasabina@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			39 => 
            array (
                'name' => 'Jakub Šturmankin',
                'email' => 'jakubsturmankin@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			40 => 
            array (
                'name' => 'Michaela Turisová',
                'email' => 'michaelaturisova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			41 => 
            array (
                'name' => 'Zuzana Viestová',
                'email' => 'zuzka.viestova@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
			42 => 
            array (
                'name' => 'Alexandra Zajaková',
                'email' => 'alexandrazajakova1@gmail.com',
                'password' => '$2y$10$qOj1iMALDTewL.Njs1dj0uoAXZmysxMAweCfoa3zg2O.gT/uwC5em',
                'remember_token' => '',
                'user_type_id' => 2,
                'created_at' => '2020-03-01 15:36:38',
                'updated_at' => '2020-03-01 15:36:38',
                'deleted_at' => NULL,
                'confirm_private_policy' => false,
				'organization_id' => 3,
				'class' => '1A - A. skupina',
            ),
        ));
        
        
    }
}