image:
  name: alpine/git:latest
  entrypoint: [""]

before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apk add openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$USER_PASS" | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_stage:
  stage: deploy
  script:
    - ssh ubuntu@team09-19.studenti.fiit.stuba.sk "cd /var/www/team-project && git checkout develop && git pull origin develop && exit"
  environment:
    name: staging
    url: http://databanka.tp
  only:
    - develop

#deploy_prod:
#  stage: deploy
#  script:
#    - ssh ubuntu@team09-19.studenti.fiit.stuba.sk "cd /var/www/team-project && git checkout develop && git pull origin develop && exit"
#  environment:
#    name: production
#    url: http://databanka.tp
#  when: manual
#  only:
#    - master